logging:
  level:
    reator:
      netty:
        channel: DEBUG
users-url: http://localhost:8081/users
messages-url: http://localhost:8082/messages
tenants-url: http://localhost:8083/tenants

spring:
  security:
    oauth2:
      client:
        provider:
          widgets:
            issuer-uri: http://idp:9999/auth/realms/widgets
            user-name-attribute: email
          toasters:
            issuer-uri: http://idp:9999/auth/realms/toasters
          socks:
            issuer-uri: http://idp:9999/auth/realms/socks
        registration:
          widgets:
            client-id: spring-security
            client-secret: d1a8feec-9505-4241-a2ef-32bbabdd8f98
            scope: openid,message:read
          toasters:
            client-id: spring-security
            client-secret: bfbd9f62-02ce-4638-a370-80d45514bd0a
          socks:
            client-id: spring-security
            client-secret: bfbd9f62-02ce-4638-a370-80d45514bd0a